# Generated by Django 5.0.2 on 2024-02-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('head_title', models.CharField(max_length=500)),
                ('keywords', models.TextField()),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=500)),
                ('preview_img', models.ImageField(upload_to='articles_images')),
                ('subtitle', models.CharField(max_length=500)),
                ('photo_text', models.TextField()),
                ('markup', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles_images')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
    ]
